
; ============================================================================
; PlatformIO Project Configuration File
; River Cleaning Boat Controller by HimalixLabs
; Board: ESP8266 NodeMCU v1.0 (ESP-12E Module)
; ============================================================================

[platformio]
default_envs = nodemcuv2
src_dir = src

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

; Serial Monitor Options
monitor_speed = 115200
monitor_filters = esp8266_unhandled_exception, default

; Upload Options
upload_speed = 921600

; Build Flags
build_flags = 
    -D ESP8266
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS
